DROP DATABASE IF EXISTS express_cc;
CREATE DATABASE express_cc;

USE express_cc;

CREATE TABLE users(
	userID INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(15) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(100),
	UNIQUE(username, email),
	PRIMARY KEY (userID)
);

CREATE TABLE posts(
	postID INT NOT NULL AUTO_INCREMENT,
	TIMESTAMP,
	post VARCHAR(1000) NOT NULL,
	PRIMARY KEY (postID),
	FOREIGN KEY (userID) REFERENCES users(userID),
	FOREIGN KEY (commentID) REFERENCES comments(commentID)
);

CREATE TABLE comments(
	commentID INT NOT NULL AUTO_INCREMENT,
	TIMESTAMP,
	comment VARCHAR(1000) NOT NULL,
	PRIMARY KEY (commentID),
	FOREIGN KEY (userID) REFERENCES users(userID)
);