DROP DATABASE IF EXISTS express_cc;
CREATE DATABASE express_cc;

USE express_cc;

CREATE TABLE users(
	userID INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(15) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password BINARY (100),
	CONSTRAINT users_uc UNIQUE (username, email),
	PRIMARY KEY (userID)
);

CREATE TABLE posts(
	postID INT NOT NULL AUTO_INCREMENT,
	username VARCHAR (15) NOT NULL,
	post TEXT (1000) NOT NULL,
	ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (username) REFERENCES users(username),
	PRIMARY KEY (postID)
);


CREATE TABLE comments(
	commentID INT NOT NULL AUTO_INCREMENT,
	username VARCHAR (15) NOT NULL,
	comment TEXT (1000) NOT NULL,
	ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,	
	FOREIGN KEY (username) REFERENCES posts(username),
	PRIMARY KEY (commentID)
);